#-------------------------------
# General Site Settings

title: Puran Pun
description: Thinker // Creator // Dreamer
email: puranmgr@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Photos, url: '#photos'}
- {name: Messages, url: '#messages'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Puran currently studies **BSc (Hons) Business Information
    Technology** at Bournemouth University. When he's not chained
    to assignments and deadlines, Puran can be found with a guitar in his
    hand or running around a football pitch.

  View my work on [GitHub](https://github.com/puranmgr){:target="_blank"}.


skills:
- {name: Communication, value: '7'}
- {name: Organization, value: '8'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Sarangkot, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Camden, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Fewa Tal, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Durdle Door, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Amsterdam, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Pokhara, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Seven Sisters, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Bournemouth, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'kevin.jpg',
  name: 'Kevin Rai',
  title: 'Metanoia Records',
  quote: '<p><strong>BUNS</strong> for the win! We initially met and performed music together through Bournemouth Nepalese Uni society and have formed strong friendship ever since.</p>',
  logo: 'logo1.png'}
- {avatar: 'laure.jpg',
  name: 'Devendra Thapa',
  title: 'Computer Science MSc (PGCert PGDip)',
  quote: '<p><strong>Gym, football and coding buddy.</strong> Brothers with same visions and interests. #southam</p>',
  logo: 'logo2.png'}
- {avatar: 'sujata.jpg',
  name: 'Sujata Thapa',
  title: 'BA (Hons) International Hospitality Management',
  quote: '<p>Our time together is <strong>limited,</strong> but I know he is only a phone call or a text away at any given time. Always there to perk your funny days or strike your "go getter" attitude up a notch.</p>',
  logo: 'logo3.png'}
- {avatar: 'thaman.jpg',
  name: 'Thaman Pun',
  title: 'PGGMB',
  quote: '<p><strong>Best mate since school!</strong> Thanks to the web, we are still in touch frequently despite being hundred miles further apart. Possible trip to Berlin? </p>',
  logo: 'logo4.png'}
